### ISSUE TITLE
Añadir codigo

### ISSUE THREAD

**Issue by juchebo1** [juchebo1/pgpilab8#1]
@ostua La primera tarea sera añadir el codigo de la ultima sesion para poder continuar trabajando. Esta tarea la hare yo.

**Comment by binedu** [comment]
Ok GI! :D

**Comment by antoniomanuelnd** [comment]
Ánimo, créalo :+1:

**Comment by binedu** [comment]
Dice el enunciado que tenemos que discutir por aquí (por issues del GI) quién hace qué. Propongo como primer añadido que Antonio compile (ejecutando make) y añada .gitignore de los archivos resultantes.

**Comment by antoniomanuelnd** [comment]
Se intentará!

**Comment by juchebo1** [comment]
Tarea completada, el resto de tareas se mencionaran en otros issues
