### ISSUE TITLE
Arreglar errores

### ISSUE THREAD

**Issue by juchebo1** [juchebo1/pgpilab8#2]
Que alguien se encargue arreglar los errores mas basicos, sobretodo la parte del autor del proyecto y diferencias asi.

**Comment by antoniomanuelnd** [comment]
He visto que hay dos archivos readme.md, tendremos que quedarnos con el correcto

**Comment by binedu** [comment]
El README (mayúsculas) está casi vacío. Me encargo yo de eliminarlo.

**Comment by juchebo1** [comment]
Ese es el archivo readme para el proyecto, el que esta mal es el que esta escrito en minusculas
